{% set name = "questo" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/questo-{{ version }}.tar.gz
  sha256: a22dced0c4912919c0c0f7912ecd604ac1f2d3492e45e9d172baf5fa10ded75d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7.8,<4.0.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.8,<4.0.0
    - rich >=12.2.0
    - python-yakh >=0.3.2,<0.4.0

test:
  imports:
    - questo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petereon/questo
  summary: A library of extensible and modular CLI prompt elements
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
