{% set name = "questo" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/questo-{{ version }}.tar.gz
  sha256: 7eb4861f814ad775e45d1fdae020a06093d4322b427cddac655fa274d82d3114

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7.8,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.8,<3.12
    - rich >=12.2.0
    - python-yakh >=0.3.2,<0.4.0

test:
  imports:
    - questo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petereon/questo
  summary: A library of extensible and modular CLI prompt elements
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
